---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Terminal

dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 1
  - name: "Tabby"
    path: "/Applications/Tabby.app/"
    pos: 2
  - name: "Boop"
    path: "/Applications/Boop.app/"
    pos: 3
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app"
    pos: 4
  - name: "Mail"
    path: "/System/Applications/Mail.app"
    pos: 5
  - name: "Kalender"
    path: "/System/Applications/Calendar.app"
    pos: 6
  - name: "KeePassXC"
    path: "/Applications/KeePassXC.app"
    pos: 7
  - name: "Nextcloud"
    path: "/Users/philipp/Nextcloud"
    pos: 8
  - name: "Downloads"
    path: "/Users/philipp/Downloads"
    pos: 9

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/github/dotfiles
dotfiles_files:
  - .osx

homebrew_installed_packages:
  - python@3.9
  - cairo
  - cowsay
  - git
  - gobuster
  - htop
  - httpie
  - ipcalc
  - iperf3
  - jq
  - libgit2
  - libpq
  - mas
  - nghttp2
  - nmap
  - node
  - pandoc
  - pwgen
  - r
  - speedtest-cli
  - telnet
  - tldr
  - tree
  - wakeonlan
  - watch
  - wget
  - zabbix-cli
  - zeromq

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - google-chrome
  - docker
  - firefox
  - slack
  - keepassxc
  - tabby

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1037126344, name: "Apple Configurator 2" }
  - { id: 562184107, name: "LanScan Pro" }
  - { id: 784801555, name: "Microsoft OneNote" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 409907375, name: "Remote Desktop" }
  - { id: 425424353, name: "The Unarchiver" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
