---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true
# Configure oh-my-zsh
configure_omz: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockutil_install: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Terminal
  - Numbers
  - Keynote
  - Musik
  - Pages
  - Karten
  - Fotos
  - FaceTime
  - Notizen
  - Erinnerungen
  - Kontakte
  - Nachrichten
  - Safari

dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 1
  - name: "Tabby"
    path: "/Applications/Tabby.app/"
    pos: 2
  - name: "Boop"
    path: "/Applications/Boop.app/"
    pos: 3
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app"
    pos: 4
  - name: "Mail"
    path: "/System/Applications/Mail.app"
    pos: 5
  - name: "Kalender"
    path: "/System/Applications/Calendar.app"
    pos: 6
  - name: "Spotify"
    path: "/Applications/Spotify.app"
    pos: 7
  - name: "KeePassXC"
    path: "/Applications/KeePassXC.app"
    pos: 8
  - name: "Nextcloud"
    path: "/Users/philipp/Nextcloud"
    pos: 9
  - name: "Downloads"
    path: "/Users/philipp/Downloads"
    pos: 10

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/p3l1/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/github/dotfiles
dotfiles_files:
  - .osx
  - .zshrc
  - .gitconfig

homebrew_installed_packages:
  - git
  - python@3.10
  - htop
  - httpie
  - ipcalc
  - iperf3
  - jq
  - mas
  - nmap
  - pwgen
  - tree
  - watch
  - wget
  - hudochenkov/sshpass/sshpass
  - ansible
  - ansible-lint
  - yamllint
  - thefuck
  - mitmproxy
  - molecule
  - romkatv/powerlevel10k/powerlevel10k
  - defaultbrowser

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - keepassxc
  - tabby
  - spotify
  - visual-studio-code
  - nextcloud
  - discord
  - obsidian
  - postman
  - anki

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1444383602, name: "Good Notes" }
  - { id: 409183694, name: "Keynote" }
  - { id: 1518425043, name: "Boop" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
- name: "molecule[docker]"
  state: present

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - zsh-plugins.yml
  - default-browser.yml

# Configure oh-my-zsh
# Default theme
oh_my_zsh_theme: powerlevel10k/powerlevel10k

# Default plugins
oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions
  - docker
  - ansible
  - httpie
  - nmap
  - history
  - brew

# Wether to install by default for all specified users.
# May be overridden by `oh_my_zsh: install:` under each user.
oh_my_zsh_install: yes

# User configuration
# Important: oh-my-zsh is installed per user so you need to specify the users to install it for.
users:
  - username: philipp
